### ISSUE TITLE
Txn no longer implements Datastore

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-datastore#114]
See: https://github.com/ipfs/go-datastore/pull/113.

Basically, `Datastore` now requires `Close` and transactions don't implement it. We *could* make `Close` a synonym for `Discard()` but that seems weird.

**Comment by bigs** [comment]
yeah, this sounds reasonable. discard/commit have more nuanced semantics than close, so i don't think it's worth merging. are there any action items from this? just patrol for breakage?

**Comment by raulk** [comment]
I think it's clearer anyway to denormalise `Txn` into `Reader` and `Writer`. I'm happy with https://github.com/ipfs/go-datastore/pull/113 and don't think there are any further action items.

**Comment by Stebalien** [comment]
SGTM. We can revisit this if we run into trouble.
