### ISSUE TITLE
v0.4.4 Test Suite Takes Ages To Run Sometimes Not Completing

### ISSUE THREAD

**Issue by bonedaddy** [ipfs/go-datastore#155]
While working on some datastore repositories, specifically my badgerv2 repo, I upgraded dependencies to v0.4.4 and ran the test suite included in this repository. It was running for 10 minutes before I killed the process because I found it incredibly strange that it was running that long.

I reverted the dependency to v0.3.1 and tests ran in 120.434s. What's the reasoning for the tests taking so long? It's nigh impossible to the tests in TravisCI because if my laptop takes this long, there is no way TravisCI will be even close. Specs:

* CPU: i7-9750H
* Memory: 32GB 
* Disk: 256GB NVMe SSD

Is this intentional? Is there any way to make this faster? I noticed the test that was being ran and not ever completing is https://github.com/ipfs/go-datastore/blob/master/test/suite.go#L16 it just seems very strange that between 0.3.1 and 0.4.4 the test suite now runs 10x as long. 

edit:

Doing some additional testing, this appears to be the same problem on `0.4.0` as there is with `0.4.4`

**Comment by Stebalien** [comment]
This looks like a serious performance regression in badger2. The test suite completes in 15 seconds on badger 1.6.1.

**Comment by Stebalien** [comment]
Wait, no, it completes in 16 seconds on badger2. Are you using https://github.com/ipfs/go-ds-badger2?

**Comment by bonedaddy** [comment]
No I'm using a fork that doesn't use `goprocess` and I'm on `v2.0.3` for badger where the `badger2` repo is using `v2.0.1-rc1`

edit: fork https://github.com/RTradeLtd/go-datastores/blob/master/badger/datastore.go

**Comment by bonedaddy** [comment]
I get the same problem using `go-ds-badger2` .

edit: Yea I don't think this is related to the fork I'm using as I'm getting the exact same problem on `go-ds-badger2`, and my fork. Something is very off

**Comment by hsanjuan** [comment]
Are the tests just progressing slowly or hanging?

**Comment by bonedaddy** [comment]
@hsanjuan Starting with v0.4.0 the `SubtestCombination` tests will start out fast, and then get proggressively slower. I can replicate this with my fork of badger datastore, and upstream badger datastore.  As far as I can tell all the other subtests appear to be okay, it's just the Combinations one

@Stebalien Not sure why the issue is closed? This problem still exists

**Comment by Stebalien** [comment]
This looks like an issue in your fork, possibly a resource leak. The tests pass in seconds on flatfs, badgerds, leveldb, sql, etc.

**Comment by bonedaddy** [comment]
> I get the same problem using `go-ds-badger2` .
> 
> edit: Yea I don't think this is related to the fork I'm using as I'm getting the exact same problem on `go-ds-badger2`, and my fork. Something is very off

As mentioned here I'm getting the exact same issue with upstream so I think this issue is still very valid. This is happening in more than just my fork so I disagree the problem is isolated to my fork

**Comment by Stebalien** [comment]
So you're saying that checking out go-ds-badger2 and running `go test -run TestSuite` is hanging? No go mod changes, no replaced dependencies, etc?

**Comment by Stebalien** [comment]
That is, https://github.com/ipfs/go-ds-badger2?

**Comment by Stebalien** [comment]
Wait, are you trying to run these tests with the race detector enabled?

**Comment by bonedaddy** [comment]
> So you're saying that checking out go-ds-badger2 and running `go test -run TestSuite` is hanging? No go mod changes, no replaced dependencies, etc?

Yes* with the exception of `go test -race ` being used

> That is, https://github.com/ipfs/go-ds-badger2?

Yes

> Wait, are you trying to run these tests with the race detector enabled?

Yep I typically dont run tests without the race detector enabled. It takes longer but generally it seems to be safer. What I'm confused on is how between v0.3.1 and v0.4.4 this lead to tests never completing. As far as I can tell in any the releases between 0.3.1 and 0.4.4 `SubtestCombinations` were updated but these are the tests that are hanging.

**Comment by bonedaddy** [comment]
I just tried without `-race` on `go-ds-badger2` and its still hanging :/

```
<@go-ds-badger2>-<⎇ master>-1-> time go test -run TestSuite ./...
^CCommand exited with non-zero status 1
46.50user 19.81system 9:24.84elapsed 11%CPU (0avgtext+0avgdata 245772maxresident)k
120inputs+865312outputs (2major+143881minor)pagefaults 0swaps
```

**Comment by Stebalien** [comment]
Very strange. What OS? What exact commit?

Could you try blowing away your go mod cache?

**Comment by Stebalien** [comment]
And could you try bisecting the go-datastore commit that introduced this issue?

**Comment by bonedaddy** [comment]
Yea its extremely weird, I even made sure to run this while in nvidia graphics mode to avoid anything that could be consuming CPU cycles.

OS:
```
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```

Kernel:
```
Linux gray 5.3.0-7642-generic #34~1584408018~19.10~21df4b1-Ubuntu SMP Tue Mar 17 13:38:51 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

Dependency from `go.sum`:

```
github.com/ipfs/go-datastore v0.4.1 h1:W4ZfzyhNi3xmuU5dQhjfuRn/wFuqEE1KnOmmQiOevEY=
github.com/ipfs/go-datastore v0.4.1/go.mod h1:SX/xMIKoCszPqp+z9JhPYCmoOoXTvaa13XEbGtsFUhA=
```
I ran `go clean --modcache` and reran the test with the same reuslts :(

> And could you try bisecting the go-datastore commit that introduced this issue?

Yep will do this today

# Switch to v0.3.1 Example

And here's me switching to `v0.3.1` and its working


```
<@go-ds-badger2>-<⎇ master>-1-> go get github.com/ipfs/go-datastore@v0.3.1
<@go-ds-badger2>-<⎇ master>-<±>-> time go test -run TestSuite ./...
ok  	github.com/ipfs/go-ds-badger2	116.508s
19.41user 6.10system 1:57.62elapsed 21%CPU (0avgtext+0avgdata 191220maxresident)k
1064inputs+370904outputs (1major+142211minor)pagefaults 0swaps
```

**Comment by Stebalien** [comment]
Which go versoin?

**Comment by Stebalien** [comment]
Also, it looks like you may be affected by https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug. Not sure if it's related (but it could cause stalls).

**Comment by bonedaddy** [comment]
> Which go versoin?
```
go version go1.14.1 linux/amd64
```

> Also, it looks like you may be affected by https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug. Not sure if it's related (but it could cause stalls).

Not sure if this would relate, but I am definitely effected by the bug as it has caused problems previously.

**Comment by bonedaddy** [comment]
I found the bad commit:
```
b026bf405c4774df1b09295cdad508727ef394d2
```

If I run `go-ds-badger2` with `go-datastore` at this commit the problematic behavior starts

**Comment by Stebalien** [comment]
> b026bf405c4774df1b09295cdad508727ef394d2

That shouldn't make _that_ much of a difference. Try setting `go-datastore/test.ElemCount` to something lower like 50. Does that help?

> go version go1.14.1 linux/amd64

FYI, go 1.14.1 has a scheduler deadlock in timers (fixed by go 1.14.2). I don't think that'll be related, but it could be.

**Comment by Stebalien** [comment]
Could you try running:

```
go test -run TestSuite`
```

Wait for it to hang for a while, then send SIGQUIT (`ctrl+q`) and post the stack traces?

**Comment by bonedaddy** [comment]
I'll try upgrading to go 1.14.2 to see what happens. I left a `go test ./...` running before my dog walk, ill do the the `go test -run TestSuite` now.

Here's the stack trace from `go test./....` from `v0.4.4` without any modifications.

```
<@go-ds-badger2>-<⎇ master>-> go test ./...
panic: test timed out after 10m0s

goroutine 852716 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1460 +0xdf
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000232120, 0xabbfe4, 0x9, 0xae1d38, 0x495301)
	/usr/local/go/src/testing/testing.go:1044 +0x37e
testing.runTests.func1(0xc00014cd80)
	/usr/local/go/src/testing/testing.go:1285 +0x78
testing.tRunner(0xc00014cd80, 0xc00018de10)
	/usr/local/go/src/testing/testing.go:992 +0xdc
testing.runTests(0xc000133500, 0xf14860, 0x12, 0x12, 0x0)
	/usr/local/go/src/testing/testing.go:1283 +0x2a7
testing.(*M).Run(0xc00017c400, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x15f
main.main()
	_testmain.go:78 +0x135

goroutine 19 [select, 9 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc00011d680)
	/home/solidity/go/pkg/mod/github.com/ipfs/go-log@v1.0.3/writer/writer.go:71 +0x128
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/home/solidity/go/pkg/mod/github.com/ipfs/go-log@v1.0.3/writer/writer.go:36 +0xb9

goroutine 617 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00014c900, 0xee5538, 0x35, 0xc0056142c0, 0xc0056ca601)
	/usr/local/go/src/testing/testing.go:1044 +0x37e
github.com/ipfs/go-datastore/test.SubtestAll(0xc000232120, 0xb92020, 0xc005781b60)
	/home/solidity/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/test/suite.go:56 +0x8f
github.com/ipfs/go-ds-badger2.TestSuite(0xc000232120)
	/home/solidity/Code/ipfs/go-ds-badger2/ds_test.go:830 +0x73
testing.tRunner(0xc000232120, 0xae1d38)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357

goroutine 618 [select]:
github.com/dgraph-io/badger/v2/y.(*WaterMark).process(0xc006ffc340, 0xc0056ca340)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/y/watermark.go:229 +0x2d7
created by github.com/dgraph-io/badger/v2/y.(*WaterMark).Init
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/y/watermark.go:78 +0xa6

goroutine 691 [chan receive, 9 minutes]:
github.com/dgraph-io/badger/v2.(*valueLog).waitOnGC(0xc000022660, 0xc0056ca6a0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/value.go:1767 +0x63
created by github.com/dgraph-io/badger/v2.Open
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:399 +0x1181

goroutine 621 [select]:
github.com/dgraph-io/badger/v2.(*levelsController).runWorker(0xc006e08300, 0xc0056ca5a0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:361 +0x20c
created by github.com/dgraph-io/badger/v2.(*levelsController).startCompact
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:342 +0x88

goroutine 690 [select]:
github.com/dgraph-io/badger/v2.(*DB).doWrites(0xc000022480, 0xc0056ca680)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:802 +0x3fa
created by github.com/dgraph-io/badger/v2.Open
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:395 +0xf59

goroutine 693 [select, 9 minutes]:
github.com/ipfs/go-ds-badger2.(*Datastore).periodicGC(0xc005781b60)
	/home/solidity/Code/ipfs/go-ds-badger2/datastore.go:168 +0x103
created by github.com/ipfs/go-ds-badger2.NewDatastore
	/home/solidity/Code/ipfs/go-ds-badger2/datastore.go:156 +0x398

goroutine 710 [chan receive]:
testing.(*T).Run(0xc0014dafc0, 0xc0027cc960, 0x54, 0xc0027c5880, 0xab7c18)
	/usr/local/go/src/testing/testing.go:1044 +0x37e
github.com/ipfs/go-datastore/test.SubtestCombinations.func2(0xc000028390, 0x6, 0x6)
	/home/solidity/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/test/basic_tests.go:278 +0x3c8
github.com/ipfs/go-datastore/test.perms(0xc0001bfe88, 0xc0001bfd48, 0x6, 0x6)
	/home/solidity/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/test/basic_tests.go:298 +0x8c
github.com/ipfs/go-datastore/test.SubtestCombinations(0xc00014c900, 0xb92020, 0xc005781b60)
	/home/solidity/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/test/basic_tests.go:267 +0x60b
github.com/ipfs/go-datastore/test.SubtestAll.func1(0xc00014c900)
	/home/solidity/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/test/suite.go:57 +0x4e
testing.tRunner(0xc00014c900, 0xc0056142c0)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357

goroutine 692 [select, 9 minutes]:
github.com/dgraph-io/badger/v2.(*publisher).listenForUpdates(0xc0001c8750, 0xc0056ca6c0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/publisher.go:67 +0x161
created by github.com/dgraph-io/badger/v2.Open
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:403 +0x1038

goroutine 622 [select]:
github.com/dgraph-io/badger/v2.(*levelsController).runWorker(0xc006e08300, 0xc0056ca5a0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:361 +0x20c
created by github.com/dgraph-io/badger/v2.(*levelsController).startCompact
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:342 +0x88

goroutine 620 [select]:
github.com/dgraph-io/badger/v2.(*DB).updateSize(0xc000022480, 0xc0056ca3a0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:1123 +0x149
created by github.com/dgraph-io/badger/v2.Open
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:344 +0x9b3

goroutine 623 [chan receive, 9 minutes]:
github.com/dgraph-io/badger/v2.(*DB).flushMemtable(0xc000022480, 0xc0056ca5c0, 0x0, 0x0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:1030 +0xb7
github.com/dgraph-io/badger/v2.Open.func4(0xc000010138)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:361 +0x37
created by github.com/dgraph-io/badger/v2.Open
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:360 +0x1474

goroutine 625 [select, 9 minutes]:
github.com/dgraph-io/badger/v2.(*valueLog).flushDiscardStats(0xc000022660)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/value.go:1864 +0x175
created by github.com/dgraph-io/badger/v2.(*valueLog).open
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/value.go:1094 +0x6c

goroutine 619 [select]:
github.com/dgraph-io/badger/v2/y.(*WaterMark).process(0xc006ffc380, 0xc0056ca340)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/y/watermark.go:229 +0x2d7
created by github.com/dgraph-io/badger/v2/y.(*WaterMark).Init
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/y/watermark.go:78 +0xa6

goroutine 852357 [semacquire]:
sync.runtime_Semacquire(0xc005d700f8)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc005d700f0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/dgraph-io/badger/v2.(*request).Wait(0xc005d700c0, 0xa1f5a0, 0xc0028cc3f0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/value.go:1309 +0x31
github.com/dgraph-io/badger/v2.(*Txn).commitAndSend.func1(0xc0028a9f80, 0xc00280fee0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/txn.go:503 +0x40
github.com/dgraph-io/badger/v2.(*Txn).Commit(0xc0028a9f80, 0x0, 0x0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/txn.go:556 +0xc4
github.com/ipfs/go-ds-badger2.(*txn).commit(...)
	/home/solidity/Code/ipfs/go-ds-badger2/datastore.go:770
github.com/ipfs/go-ds-badger2.(*Datastore).Put(0xc005781b60, 0xc0027e18b0, 0x10, 0xc0027eeac0, 0x40, 0x40, 0x0, 0x0)
	/home/solidity/Code/ipfs/go-ds-badger2/datastore.go:224 +0x193
github.com/ipfs/go-datastore/test.subtestQuery(0xc0014dafc0, 0xb92020, 0xc005781b60, 0x0, 0x0, 0xc00006a2c0, 0x1, 0x1, 0xc00006a3c0, 0x1, ...)
	/home/solidity/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/test/basic_tests.go:432 +0xdf3
github.com/ipfs/go-datastore/test.SubtestCombinations.func2.1(0xc0014dafc0)
	/home/solidity/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/test/basic_tests.go:279 +0xad
testing.tRunner(0xc0014dafc0, 0xc0027c5880)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357

goroutine 852653 [syscall]:
syscall.Syscall(0x1, 0xa, 0xc002a0a540, 0x83, 0x19, 0x80000000000, 0x7ffff80000000000)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.write(0xa, 0xc002a0a540, 0x83, 0xc0, 0x0, 0x62, 0x62)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:914 +0x5a
syscall.Write(...)
	/usr/local/go/src/syscall/syscall_unix.go:214
internal/poll.(*FD).Write(0xc005781a40, 0xc002a0a540, 0x83, 0xc0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:268 +0x179
os.(*File).write(...)
	/usr/local/go/src/os/file_unix.go:280
os.(*File).Write(0xc0000101c0, 0xc002a0a540, 0x83, 0xc0, 0x1, 0x1, 0x4)
	/usr/local/go/src/os/file.go:153 +0x77
github.com/dgraph-io/badger/v2.(*valueLog).write.func1(0xc000095a00, 0x1880)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/value.go:1383 +0x140
github.com/dgraph-io/badger/v2.(*valueLog).write.func2(0xc0000ba5a0, 0xc002a0e060)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/value.go:1396 +0x3c
github.com/dgraph-io/badger/v2.(*valueLog).write(0xc000022660, 0xc0028babe0, 0x1, 0xa, 0x0, 0x0)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/value.go:1461 +0x538
github.com/dgraph-io/badger/v2.(*DB).writeRequests(0xc000022480, 0x0, 0x1, 0xa, 0x449186, 0xae2658)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:717 +0x106
github.com/dgraph-io/badger/v2.(*DB).doWrites.func1(0xc0028babe0, 0x1, 0xa)
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:789 +0x5a
created by github.com/dgraph-io/badger/v2.(*DB).doWrites
	/home/solidity/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:842 +0x30e
FAIL	github.com/ipfs/go-ds-badger2	600.011s
FAIL
```

> That shouldn't make that much of a difference. Try setting go-datastore/test.ElemCount to something lower like 50. Does that help?

Doesn't appear to have made any difference

> Wait for it to hang for a while, then send SIGQUIT (ctrl+q) and post the stack traces?

`ctrl+q` was unsuccessful in quitting, `kill -3 <PID>` didnt give any stack trace just terminated the process

```
<@go-ds-badger2>-<⎇ master>-<±>-> go test -run TestSuite ./...
^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q



<@go-ds-badger2>-<⎇ master>-<±>-1-> 
```

I'll upgrade to go 1.14.2 and see what happens

**Comment by bonedaddy** [comment]
1.14.2 provides no difference

**Comment by Stebalien** [comment]
IIRC, `go test ./...` will run the actual tests in subprocesses. That's why SIGQUIT won't work.

As for the test, it's performing a put and it doesn't look like anything is stuck. I have no idea why it's taking so long.

**Comment by hsanjuan** [comment]
On go-ds-badger2 without -race things work fine for me.

With `-race` things get much much slower but don't hang and finish after a few minutes.

Can you reproduce on a different platform @bonedaddy ? I use `go1.14.1`.

Switching to v0.3.1 will solve your problem since it does not have the combinations tests I think. The question is why queries slow down so much when these run...

**Comment by bonedaddy** [comment]
> IIRC, go test ./... will run the actual tests in subprocesses. That's why SIGQUIT won't work.

Still no dice :(

```
<@go-ds-badger2>-<⎇ master>-<±>-1-> go test -run TestSuite
^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Q^Csignal: interrupt
FAIL	github.com/ipfs/go-ds-badger2	6.455s
````

> Can you reproduce on a different platform @bonedaddy ? I use go1.14.1.

Can reproduce on one of our dev boxes with the following specs:

OS:

```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Kernel:
```
Linux capecod 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

CPU:
```
2x Intel Xeon E5540
```

Memory: 70GB

Go version:

```
go version go1.13.4 linux/amd64
```



edit:

If need be I can try on one of our IPFS nodes during maintenance tonight, they're extremely beefy so might help to rule out any other possible issues

**Comment by hsanjuan** [comment]
You have SSDs right? Or are you running in spinning disks?

**Comment by bonedaddy** [comment]
> You have SSDs right? Or are you running in spinning disks?

On my laptop I ran the test off an NVMe SSD, on the dev server it was running off a RAID1 disk. On the server I'll be trying it out on tonight it will have an SSD.

**Comment by bonedaddy** [comment]
Ran it on one of our IPFS nodes with the following specs and the test still hung


Kernel:
```
Linux delta-node-2 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

OS:

```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

CPU:  2x E5-2660 v4


Disk: ran off a 256GB SSD

Memory: 128GB DDR4

Go version:

```
go version go1.14.2 linux/amd64
```

**Comment by Stebalien** [comment]
When it hangs, is the CPU doing a lot of work or is it just sitting there?

**Comment by bonedaddy** [comment]
It's just sitting there, no major CPU activity to speak of

**Comment by Stebalien** [comment]
After it does that for a while, could you try dumping the goroutine list again? That should make it clear _what's_ stuck.

**Comment by bonedaddy** [comment]
Sure I'll do that tonight. I'll increase the timeout to 20 minutes and let it timeout, or if 20 minutes is long enough, decrease the timeout until the test times out.

**Comment by bonedaddy** [comment]
Hey sorry for the delay got caught up with some other tasks, let me do this now

**Comment by bonedaddy** [comment]
@Stebalien ran for 30 minutes and it timed out, here's the goroutine dump

[test.log](https://github.com/ipfs/go-datastore/files/4556486/test.log)

**Comment by hsanjuan** [comment]
This seems like a race condition on badger-v2? I think writes are deadlocked.

Does your machine run these tests fine with badger-v1 ? (sorry if this is answered somewhere, I don't see it above but it's a long thread).

Can you actually enable debug logging in badger and see what's going on? Is it looping endessly `Making room for writes`? Can you plug to the badger stats/accounting and check the evolution of the number of pending writes?

A wild shot: can you try running with a custom badger dependency where you modify `kvWriteChCapacity` (https://github.com/dgraph-io/badger/blob/v2.0.3/db.go#L99) to 10, 100, 1000, 100000 and see what happens on the different values?

If the datastore suite works in badgerv1 but not in badgerv2, you probably need to report this upstream. With the current info, this seems a badger issue out of the scope of go-datastore. Our tests are just reproducing it in some setups.

Check the above suggestions and try debugging badgerv2 yourself a bit more please. We cannot sink much more time debugging something that we don't even support.

**Comment by bonedaddy** [comment]
> This seems like a race condition on badger-v2? I think writes are deadlocked
> Does your machine run these tests fine with badger-v1 ? (sorry if this is answered somewhere, I don't see it above but it's a long thread).

I can reproduce on badger-v1, and badger-v2. Interestingly enough running the test suite on `go-ds-leveldb` takes about 4 seconds to complete. 

I'll try the other suggestions you have to see if this helps narrow down the issue, but it's starting to look like the problem is within badger itself whether its v1 or v2

**Comment by bonedaddy** [comment]
Here's the goroutine dump from badger-v1

[test.log](https://github.com/ipfs/go-datastore/files/4561412/test.log)

**Comment by bonedaddy** [comment]
Found the cause this is a repeat of https://github.com/dgraph-io/badger/issues/1084

**Comment by Stebalien** [comment]
Interesting. But that doesn't really explain why it's still fast on _my_ linux system.

Note: go-ipfs now disables sync writes by default and calls `Sync` before and after it pins.
