### ISSUE TITLE
v0.4.4 Causes TestSuite Slowness In SubtestCombinations In A Variety Of Different Datastores

### ISSUE THREAD

**Issue by bonedaddy** [ipfs/go-datastore#156]
The last issue was closed because of it "being a problem in my fork" despite  witnessing the problem in upstream badger datastore. So far I have observed this problem in in both [go-ds-badger2](https://github.com/ipfs/go-ds-badger2) as well as [my fork](https://github.com/RTradeLtd/go-datastores/blob/master/badger/datastore.go). 

Please don't close this issue again because "it's just happening in my fork" that's blatantly false as I'm observing this in my fork, and upstrea.

# Original Issue

While working on some datastore repositories, specifically my badgerv2 repo, I upgraded dependencies to v0.4.4 and ran the test suite included in this repository. It was running for 10 minutes before I killed the process because I found it incredibly strange that it was running that long.

I reverted the dependency to v0.3.1 and tests ran in 120.434s. What's the reasoning for the tests taking so long? It's nigh impossible to the tests in TravisCI because if my laptop takes this long, there is no way TravisCI will be even close. Specs:

* CPU: i7-9750H
* Memory: 32GB 
* Disk: 256GB NVMe SSD

Is this intentional? Is there any way to make this faster? I noticed the test that was being ran and not ever completing is https://github.com/ipfs/go-datastore/blob/master/test/suite.go#L16 it just seems very strange that between 0.3.1 and 0.4.4 the test suite now runs 10x as long.

**Comment by Stebalien** [comment]
There's no need to open a new issue. However, you clearly stated that you _were_ using a fork.

Closing and reopening https://github.com/ipfs/go-datastore/issues/155.
