### ISSUE TITLE
Vendoring dependencies

### ISSUE THREAD

**Issue by btc** [ipfs/go-datastore#3]
Build is failing. elastigo at fault. Attempted to bisect elastigo to find working version. All attempts fail to build. Next step: linear scan.

Figured I would ping here in case you happen to have a working version of elastigo you can identify for the purpose of setting up vendoring.

**Comment by jbenet** [comment]
Builds with 041b88c -- not sure what bugs/feats have happened since then (omfg packaging in go).

**Comment by jbenet** [comment]
https://github.com/mattbaird/elastigo/tree/041b88c/

**Comment by btc** [comment]
addressed in https://github.com/jbenet/datastore.go/pull/5

(locks and vendors elastigo @ 041b88c)

**Comment by jbenet** [comment]
thanks @perfmode
