### ISSUE TITLE
Checkin result of `gx-go rewrite`?

### ISSUE THREAD

**Issue by kevina** [ipfs/go-datastore#42]
The build process does a `gx-go rewrite` which of causes a lot of diff noise.  Now when I want to submit a pull request I got to be careful not check in the changes imports.

Should the results of `gx-go rewrite` just be check in like it is in go-ipfs to avoid this problem?

**Comment by Kubuxu** [comment]
In general our projects are in non-rewritten state. Only go-ipfs is special as we don't want people to build it with wrong deps.

You can add `gx-go rewrite --undo` to your pre-commit git hook.

**Comment by kevina** [comment]
Okay, if that is the general policy.  It seams a bit of a hack to have to use `gx-go rewrite --undo`.  It also, in my view,  touches a lot of files unnecessary.

**Comment by whyrusleeping** [comment]
we dont commit the rewritten paths because that makes any updates to the package dependencies generate huge messy diffs and makes review much more tedious.

**Comment by kevina** [comment]
I understand, it is a tradeoff.  There seams like there should be a better way to manage dependencies than rewriting code.  In any case this is a gx issue, so closing.
