### ISSUE TITLE
split out subpackages into separate packages

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-datastore#47]
Updating portions of this codebase would be much easier if some of the more used subcomponents were extracted, such as flatfs and leveldb.

Restricting this package to an interface definition and some small 'stock' implementations would also greatly improve the dependency tree of any application wanting to make use of this codebase

**Comment by jbenet** [comment]
Sgtm!

**Comment by whyrusleeping** [comment]
I've extracted a lot of the subrepos. Anything that had external dependencies now lives outside of this repo. I think for now, we can close this. If packages in this repo end up getting changes made to them more frequently the we should consider moving them out as well.

For now, lets close this
