### ISSUE TITLE
Document implementions of datastore

### ISSUE THREAD

**Issue by duomoney** [ipfs/go-datastore#61]
I was able to find the following backing datastore implementations:

* go-ds-leveldb
* go-ds-flatfs
* go-ds-redis

[This spec](https://github.com/ipfs/specs/blob/master/repo/fs-repo/README.md) mentions `boltdb`, but I think that's only for illustration purposes. There's also non-backing implementations:

* go-ds-lru
* go-ds-measure
* [autobatch](https://github.com/whyrusleeping/autobatch)
* [failstore](https://github.com/whyrusleeping/failstore)
* [retry-datastore](https://github.com/whyrusleeping/retry-datastore)

**Comment by hsanjuan** [comment]
Bolt is here: https://github.com/ipfs/go-ds-bolt

The full list of datastores is self-documented here by searching `go-ds` in the organization: https://github.com/ipfs?q=go-ds&type=&language=
