### ISSUE TITLE
Importing failstore, retry-datastore, autobatch

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-datastore#83]
These three are used in go-ipfs (as far as dep graph goes):

* https://github.com/whyrusleeping/autobatch
* https://github.com/whyrusleeping/failstore
* https://github.com/whyrusleeping/retry-datastore

I think they might live here as subpackages?

@Stebalien @whyrusleeping 

Alternatively I could fork them to the ipfs/ org in their own repos.

Alternatively I could get write access so I can bubble up a new go-datastore to them.

**Comment by whyrusleeping** [comment]
I think it makes sense to move them into go-datastore IFF we're confident that they won't need to be changed for a long time. And I think that is currently the case, so I'd say go ahead

**Comment by Ericson2314** [comment]
I think this can be closed?
