### ISSUE TITLE
Add TTL and Transaction support

### ISSUE THREAD

**Issue by bigs** [ipfs/go-datastore#87]
Migrating conversation from libp2p/go-libp2p-peerstore#28.

Would like to add deeper support for TTL and Transactions, specifically in the context of Badger.

This brings up a pretty relevant point/deficiency with having a single interface like `Datastore` in contexts where you really do want extra functionality: 

- If we want to have meaningful mixes of `Datastore` functionality, call sites will either have to alias their own combination or cast, i.e.
    ```golang
    type MyDs interface {
        TTLDatastore
        TransactionalDatastore
    }
    ```
    And trust that they are using the implementation correctly (Badger, for example, provides these two in a fashion that can be used in tandem.
- Create a power set of combinations (not ideal haha).
- Just use the underlying wrapping `Datastore` (i.e.`BadgerDatastore`).
- Just use the underlying database, sans `Datastore`.

In our issue, you mentioned:

> Using adapters here will actually be a bit interesting. Unlike our current adapters, these will need to store additional state. That means that if a user opens the datastore and doesn't view it through the adapter, bad things will happen. I'm not sure what the best solution is.

Definitely relevant to discuss in the context of underlying datastores that do this already and datastores we will have to extend with this behavior.

EDIT: Potential interfaces

```golang
type ExpiringDatastore interface {
    Datastore

    PutExpiring(...)
    SetExpiration(...)
}

type Txn interface {
    Datastore

    Commit(...)
    Rollback(...)
}

type TxDatastore interface {
    Datastore

    NewTransaction(...) Txn
}
```

**Comment by bigs** [comment]
@whyrusleeping @Stebalien

**Comment by Stebalien** [comment]
So, transactions in general would be really useful. Especially given the fact that we never guarantee that only a single service will be writing to some part of the datastore. However, I really don't have any concrete ideas on how to move forward.
