### ISSUE TITLE
Create standard test suite

### ISSUE THREAD

**Issue by bigs** [ipfs/go-datastore#90]
poking around the `go-ds-badger` code, i was a bit surprised to see it implements all of its own tests. i feel like we could extend the `dstest` namespace to include a broader variety of tests (that test all of the subclasses of `Datastore`, too) and simply call into those from various implementations.

**Comment by Stebalien** [comment]
I've started that in #93.

**Comment by hsanjuan** [comment]
Can be closed @Stebalien ?

**Comment by Stebalien** [comment]
Yep.
