### ISSUE TITLE
Make the datastores take/return []byte slices

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-datastore#94]
This has been bugging me for a while so I figured I'd just go ahead and do it.

**Comment by kevina** [comment]
@Stebalien there might have been a reason for the {}interface return value.  I would get the all clear from @whyrusleeping (and maybe jbenet, but don't want to bother him unless necessary) before proceeding as he would know the historical context better then either of us.  My apologizes if you already did.

**Comment by Stebalien** [comment]
Thanks for bringing that up but I have talked with juan about this. In theory, the "datastore" was supposed to support arbitrary objects. However, that doesn't work well in practice and we never actually used that feature. I'm going to get @whyrusleeping's :+1: when CI is green.

**Comment by kevina** [comment]
Okay as long as Juan and @whyrusleeping are okay with it, it sounds good to me.

**Comment by Stebalien** [comment]
Last time I checked, Juan was more resigned to it than ok but close enough.

**Comment by whyrusleeping** [comment]
Yolo

**Comment by Stebalien** [comment]
All done!
