### ISSUE TITLE
Datastores should expose Close()

### ISSUE THREAD

**Issue by raulk** [ipfs/go-datastore#97]
We should consider embedding `io.Closer` inside `Datastore` and upgrading all implementations to forward the call to the underlying closing method, as well as to perform any necessary cleanup (channels, goroutines, etc.):

* badger: https://godoc.org/github.com/dgraph-io/badger#DB.Close
* leveldb: https://godoc.org/github.com/syndtr/goleveldb/leveldb#DB.Close

**Comment by Stebalien** [comment]
YES (although we shouldn't rely on it for correctness).

**Comment by kevina** [comment]
> YES (although we shouldn't rely on it for correctness).

Can you be more specific?

**Comment by Stebalien** [comment]
We should be able to close datastores so:

1. We *can* do a clean shutdown.
2. We can open, use, and then close a datastore without shutting down.

However, we shouldn't *rely* on datastores being correctly closed on shutdown (i.e., we should be able to crash).

(nothing surprising, just not very well put)
